// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello_stream.proto

package org.demo.stream;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.demo.stream.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
