// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello_world.proto

package org.demo;

public interface HelloReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.demo.HelloReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
